// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tams.Negocio.Infrastructura.Persistence;

#nullable disable

namespace Tams.Negocio.Infrastructura.Migrations
{
    [DbContext(typeof(TamsDbContext))]
    partial class TamsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("negocio")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Tams.Negocio.Domain.Entidades.AnioEscolar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("EsActivo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("FechaFin")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("EsActivo")
                        .IsUnique()
                        .HasFilter("[EsActivo] = 1");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("AniosEscolares", "negocio", t =>
                        {
                            t.HasCheckConstraint("CK_AnioEscolar_FechaFin_MayorQue_FechaInicio", "[FechaFin] > [FechaInicio]");
                        });
                });

            modelBuilder.Entity("Tams.Negocio.Domain.Entidades.AsignacionDocente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CursoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("HorasSemanales")
                        .HasColumnType("int");

                    b.Property<int>("MateriaId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CursoId");

                    b.HasIndex("MateriaId", "CursoId")
                        .IsUnique();

                    b.ToTable("AsignacionesDocentes", "negocio", t =>
                        {
                            t.HasCheckConstraint("CK_AsignacionDocente_HorasSemanales_Positivas", "[HorasSemanales] > 0");
                        });
                });

            modelBuilder.Entity("Tams.Negocio.Domain.Entidades.BloqueHorario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AsignacionDocenteId")
                        .HasColumnType("int");

                    b.Property<bool>("Bloqueado")
                        .HasColumnType("bit");

                    b.Property<string>("DiaSemana")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<TimeOnly>("HoraFin")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("HoraInicio")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("AsignacionDocenteId");

                    b.ToTable("BloquesHorarios", "negocio", t =>
                        {
                            t.HasCheckConstraint("CK_BloqueHorario_HoraFin_MayorQue_HoraInicio", "[HoraFin] > [HoraInicio]");
                        });
                });

            modelBuilder.Entity("Tams.Negocio.Domain.Entidades.Calificacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnioEscolarId")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Borrador");

                    b.Property<int>("EstudianteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("MateriaId")
                        .HasColumnType("int");

                    b.Property<int?>("NumeroRA")
                        .HasColumnType("int");

                    b.Property<int?>("Periodo")
                        .HasColumnType("int");

                    b.Property<decimal>("PuntajeObtenido")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PuntajeRecuperacion")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TipoEvaluacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("AnioEscolarId");

                    b.HasIndex("EstudianteId");

                    b.HasIndex("MateriaId");

                    b.ToTable("Calificaciones", "negocio", t =>
                        {
                            t.HasCheckConstraint("CK_Calificacion_PuntajeObtenido_NoNegativo", "[PuntajeObtenido] >= 0");

                            t.HasCheckConstraint("CK_Calificacion_PuntajeRecuperacion_NoNegativo", "[PuntajeRecuperacion] IS NULL OR [PuntajeRecuperacion] >= 0");
                        });
                });

            modelBuilder.Entity("Tams.Negocio.Domain.Entidades.Centro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("TipoCentro")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TiposTecnicosHabilitados")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Centros", "negocio");
                });

            modelBuilder.Entity("Tams.Negocio.Domain.Entidades.Curso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnioEscolarId")
                        .HasColumnType("int");

                    b.Property<bool>("EsTecnico")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Grado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Seccion")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TipoTecnico")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("AnioEscolarId", "Grado", "Seccion")
                        .IsUnique();

                    b.ToTable("Cursos", "negocio", t =>
                        {
                            t.HasCheckConstraint("CK_Curso_TipoTecnico_SoloSiEsTecnico", "[TipoTecnico] IS NULL OR [EsTecnico] = 1");
                        });
                });

            modelBuilder.Entity("Tams.Negocio.Domain.Entidades.Estudiante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CursoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CursoId");

                    b.ToTable("Estudiantes", "negocio");
                });

            modelBuilder.Entity("Tams.Negocio.Domain.Entidades.Materia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CantidadRA")
                        .HasColumnType("int");

                    b.Property<bool>("EsTecnica")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("TipoTecnico")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Materias", "negocio", t =>
                        {
                            t.HasCheckConstraint("CK_Materia_CantidadRA_Positiva", "[CantidadRA] IS NULL OR [CantidadRA] > 0");

                            t.HasCheckConstraint("CK_Materia_CantidadRA_SoloSiEsTecnica", "[CantidadRA] IS NULL OR [EsTecnica] = 1");

                            t.HasCheckConstraint("CK_Materia_TipoTecnico_SoloSiEsTecnica", "[TipoTecnico] IS NULL OR [EsTecnica] = 1");
                        });
                });

            modelBuilder.Entity("Tams.Negocio.Domain.Entidades.AsignacionDocente", b =>
                {
                    b.HasOne("Tams.Negocio.Domain.Entidades.Curso", "Curso")
                        .WithMany("AsignacionesDocentes")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Tams.Negocio.Domain.Entidades.Materia", "Materia")
                        .WithMany("AsignacionesDocentes")
                        .HasForeignKey("MateriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Curso");

                    b.Navigation("Materia");
                });

            modelBuilder.Entity("Tams.Negocio.Domain.Entidades.BloqueHorario", b =>
                {
                    b.HasOne("Tams.Negocio.Domain.Entidades.AsignacionDocente", "AsignacionDocente")
                        .WithMany("BloquesHorarios")
                        .HasForeignKey("AsignacionDocenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AsignacionDocente");
                });

            modelBuilder.Entity("Tams.Negocio.Domain.Entidades.Calificacion", b =>
                {
                    b.HasOne("Tams.Negocio.Domain.Entidades.AnioEscolar", "AnioEscolar")
                        .WithMany("Calificaciones")
                        .HasForeignKey("AnioEscolarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Tams.Negocio.Domain.Entidades.Estudiante", "Estudiante")
                        .WithMany("Calificaciones")
                        .HasForeignKey("EstudianteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Tams.Negocio.Domain.Entidades.Materia", "Materia")
                        .WithMany("Calificaciones")
                        .HasForeignKey("MateriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AnioEscolar");

                    b.Navigation("Estudiante");

                    b.Navigation("Materia");
                });

            modelBuilder.Entity("Tams.Negocio.Domain.Entidades.Curso", b =>
                {
                    b.HasOne("Tams.Negocio.Domain.Entidades.AnioEscolar", "AnioEscolar")
                        .WithMany("Cursos")
                        .HasForeignKey("AnioEscolarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AnioEscolar");
                });

            modelBuilder.Entity("Tams.Negocio.Domain.Entidades.Estudiante", b =>
                {
                    b.HasOne("Tams.Negocio.Domain.Entidades.Curso", "Curso")
                        .WithMany("Estudiantes")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Curso");
                });

            modelBuilder.Entity("Tams.Negocio.Domain.Entidades.AnioEscolar", b =>
                {
                    b.Navigation("Calificaciones");

                    b.Navigation("Cursos");
                });

            modelBuilder.Entity("Tams.Negocio.Domain.Entidades.AsignacionDocente", b =>
                {
                    b.Navigation("BloquesHorarios");
                });

            modelBuilder.Entity("Tams.Negocio.Domain.Entidades.Curso", b =>
                {
                    b.Navigation("AsignacionesDocentes");

                    b.Navigation("Estudiantes");
                });

            modelBuilder.Entity("Tams.Negocio.Domain.Entidades.Estudiante", b =>
                {
                    b.Navigation("Calificaciones");
                });

            modelBuilder.Entity("Tams.Negocio.Domain.Entidades.Materia", b =>
                {
                    b.Navigation("AsignacionesDocentes");

                    b.Navigation("Calificaciones");
                });
#pragma warning restore 612, 618
        }
    }
}
